spring:
  application:
    name: gateway-server
  jmx:
    enabled: false

  cloud:
    gateway:
      httpclient:
        ssl:
          use-insecure-trust-manager: true
      routes:
        - id: zipkin-server
          uri: http://zipkin-server:9411
          predicates:
            - Path=/zipkin-service/**
          filters:
            - StripPrefix=1

        - id: zipkin-server-resources
          uri: http://zipkin-server:9411
          predicates:
            - Path=/zipkin/**

        - id: hello-rest-server
          uri: lb://hello-rest-server:8081
          predicates:
            - Path=/hello-service/**
          filters:
            - StripPrefix=1

        - id: eureka-server
          uri: http://eureka-server:8890
          predicates:
            - Path=/eureka-service/**
          filters:
            - StripPrefix=1

        - id: eureka-server-resources
          uri: http://eureka-server:8890
          predicates:
            - Path=/eureka/**

        - id: authorization-server
          uri: http://authorization-server:8893
          predicates:
            - Path=/authorization-service
          filters:
            - RewritePath=/authorization-service, /gate

        - id: authorization-server-resource
          uri: http://authorization-server:8893
          predicates:
            - Path=/authorization-service/**
          filters:
            - RewritePath=/authorization-service/(?<segment>.*),/gate/$\{segment}

        - id: actuator-server
          uri: http://actuator-server:8891
          predicates:
            - Path=/actuator-service
          filters:
            - RewritePath=/actuator-service, /actuator-page

        - id: actuator-server-resources
          uri: http://actuator-server:8891
          predicates:
            - Path=/actuator-service/**
          filters:
            - RewritePath=/actuator-service/(?<segment>.*),/actuator-page/$\{segment}

server:
  port: 8080

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

  tracing:
    enabled: true
    sampling.probability: 1.0

    zipkin.tracing.endpoint: http://zipkin-server:9411/api/v2/spans

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.filter: INFO
  pattern.level: "trace_id=%mdc{traceId} span_id=%mdc{spanId} trace_flags=%mdc{traceFlags} %p"
