version: '3'
services:

  eureka-server:
    container_name: eureka-server
    environment:
      - "spring_profiles_active=docker"
    build: ./eureka-server/
    #    ports:
    #      - "8890:8890"
    networks:
      - server-net

  actuator-server:
    container_name: actuator-server
    depends_on:
      - "eureka-server"
    environment:
      - "spring_profiles_active=docker"
    build: ./actuator-server/
    #    ports:
    #      - "8891:8891"
    networks:
      - server-net

  authentication-server:
    container_name: authentication-server
    depends_on:
      - "eureka-server"
    environment:
      - "spring_profiles_active=docker"
    build: ./authentication-server/
    ports:
      - "8893:8893"
    networks:
      - server-net

  hello-rest-server:
    # container_name: hello-rest-server
    depends_on:
      - "eureka-server"
    environment:
      - "spring_profiles_active=docker"
    build: ./hello-rest-server/
    deploy:
      replicas: 2
    #    ports:
    #      - "8081-8082:8081"
    networks:
      - server-net

  gateway-server:
    container_name: gateway-server
    depends_on:
      - "eureka-server"
    environment:
      - "spring_profiles_active=docker"
    build: ./gateway-server/
    ports:
      - "8080:8080"
    networks:
      - server-net

  zipkin-server:
    image: openzipkin/zipkin:2
    # ports:
    #   - '9411:9411'
    networks:
      - server-net

networks:
  server-net:
    driver: bridge
