spring:
  application:
    name: hello-rest-server

  zipkin:
    baseUrl: http://zipkin-server:9411

server:
  port: 8081

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

  tracing:
    enabled: true
    sampling.probability: 1.0

  zipkin.tracing.endpoint: http://zipkin-server:9411/api/v2/spans

logging.pattern.level: "trace_id=%mdc{traceId} span_id=%mdc{spanId} trace_flags=%mdc{traceFlags} %p"
