spring:
  application:
    name: authorization-server

server:
  port: 8893
  servlet:
    context-path: /gate

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart

management:
  server:
    port: 8894
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

  tracing:
    enabled: true
    sampling.probability: 1.0

  zipkin.tracing.endpoint: http://zipkin-server:9411/api/v2/spans

logging:
  pattern.level: "trace_id=%mdc{traceId} span_id=%mdc{spanId} trace_flags=%mdc{traceFlags} %p"
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
